baseURL: 'https://jakobj.dev/'
languageCode: 'en-us'
title: 'Jakob Johnson'
theme: "papermod"
enableEmoji: true
googleAnalytics: UA-136943577-1

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Personal Website for Jakob Johnson"
    author: Jakob Johnson
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    # comments: false
    # images: ["papermod-cover.png"]

    # profileMode:
    #     enabled: false
    #     title: PaperMod
    #     imageUrl: "#"
    #     imageTitle: my image
    #     # imageWidth: 120
    #     # imageHeight: 120
    #     buttons:
    #         - name: Archives
    #           url: archives
    #         - name: Tags
    #           url: tags

    homeInfoParams:
        Title: "Jakob Johnson"
        Content: >
            Hi, my name is Jakob Johnson. I'm a PhD student at the University of Utah
    socialIcons:
        - name: github
          url: "https://github.com/jakobottar"
        - name: email
          url: "mailto:jakobottar@pm.me"
        - name: twitter
          url: "https://twitter.com/jakobottar"
        - name: strava
          url: "https://www.strava.com/athletes/jakobottar"
