baseURL: 'https://jakobj.dev/'
languageCode: 'en-us'
title: 'Jakob Johnson'
theme: "papermod"
enableEmoji: true
googleAnalytics: UA-136943577-1
buildDrafts: true

menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 20

params:
  env: production
  description: "Personal Website for Jakob Johnson"
  author: Jakob Johnson

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: false
  displayFullLangName: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

  homeInfoParams:
    Title: "Jakob Johnson"
    Content: >
      Hi, my name is Jakob Johnson. I'm a PhD student at the University of Utah studying image processing and computer vision. Read more about me and my research [here](/about/).
  socialIcons:
    - name: github
      url: "https://github.com/jakobottar"
    - name: email
      url: "mailto:jakobottar@pm.me"
    # - name: twitter
    #   url: "https://twitter.com/jakobottar"
    - name: instagram
      url: "https://instagram.com/jakobottar"
    - name: strava
      url: "https://www.strava.com/athletes/jakobottar"
  

  assets:
    favicon: "/skier.ico"
    favicon16x16: "/skier-16x16.png"
    favicon32x32: "/skier-32x32.png"

