networks:
  web:


services:
  jakobjdev:
    container_name: website 

    image: "ghcr.io/jakobottar/jakobjdev:stable"

    networks:
      - traefik_web

    labels:
      - traefik.enable=true
      - traefik.http.routers.jakobjdev.rule=Host(`jakobj.dev`)
      - traefik.http.routers.jakobjdev.entrypoints=https
      - traefik.http.routers.jakobjdev.service=jakobjdev@internal
    restart: unless-stopped
    
## Traefik Config
# networks:
#   web:
#     driver: bridge

# services:
#   traefik:
#     container_name: traefik

#     image: traefik:latest

#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - ./traefik.yml:/config/traefik.yml
#       - ./nextcloud.yml:/dyn_conf/nextcloud.yml
#       - ./acme.json:/acme.json # must be 600 permissions

#     ports:
#       - 80:80
#       - 443:443

#     command: --api.insecure=true --configFile=/config/traefik.yml

#     networks:
#       - web

#     restart: unless-stopped
