networks:
  web:


services:
  jakobjdev:
    container_name: jakobjdev
    image: "ghcr.io/jakobottar/jakobjdev:stable"
    labels:
      - traefik.enable=true
      - traefik.http.routers.jakobjdev.rule=Host(`jakobj.dev`)
      - traefik.http.routers.jakobjdev.entrypoints=websecure
      - traefik.http.services.jakobjdev.loadbalancer.server.port=8080
      - traefik.http.routers.jakobjdev.tls.certresolver=mycerts
    networks:
      - web
    restart: unless-stopped

  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    command: --api.insecure=true --configFile=/config/traefik.yml
    networks:
      - web
    ports:
      - 80:80
      - 443:443

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/config/traefik.yml
      - ./acme.json:/acme.json # must be 600 permissions
