api:
  debug: false
  dashboard: false
global:
  sendAnonymousUsage: false
providers:
  docker: {}
ping:
  entryPoint: web
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
