log:
  level: debug
api:
  debug: false
  dashboard: false
global:
  sendAnonymousUsage: false
providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
ping:
  entryPoint: web
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443
