log:
  level: info

api:
  debug: false
  dashboard: false
  
global:
  sendAnonymousUsage: false

providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    network: website_web

ping:
  entryPoint: web

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: :443

certificatesResolvers:
  mycerts:
    acme:
      email: jakobottar@pm.me
      storage: acme.json
      httpChallenge:
        entryPoint: web

